logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 8443  
  servlet:
    context-path: /myapp
    session:
      cookie:
        path: /myapp
  ssl:
    key-store-password: ${keystorepassword}
    key-store: classpath:eventoappstore.p12
    key-store-type: PKCS12
    key-alias: tomcat
  error:
    whitelabel:
      enabled: "false"
      
eventocache:
  endpoint:
    uri: http://localhost:8585/eventoCache
    
spring:
  thymeleaf:
    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect    
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.h2.Driver
  h2:
    console:
      path: /h2-console
      enabled: true
  rabbitmq:
    host: localhost
    port: "5672"
    username: username
    password: password
    listener:
      default-requeue-rejected: "false"
      retry:
        enabled: "true"
        max-attempts: "3"
        initial-interval: "5000"       
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 366798415299-h5on1frok3jmrnog9cg35m2hkcp092jg.apps.googleusercontent.com
            client-secret: -O4njCoDfypf5ATwKQUQw_T9
            scope: openid,profile,email
            client-name: SivaGoogle
          way2learnclient:
            client-id: microclient
            client-secret: secret
            client-name: Way2learn
            scope: user_info,read
            redirect-uri: https://localhost:8443/myapp/login/oauth2/code/way2learnappclient
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            provider: way2learn-authserver-provider
        provider:
            way2learn-authserver-provider:
              token-uri: http://localhost:8081/auth/oauth/token
              authorization-uri: http://localhost:8081/auth/oauth/authorize
              user-info-uri: http://localhost:8081/auth/userinfo
              user-name-attribute: username
             
name:
  topicexchange:
    assortment: assortment-integration-exchange
  routingKey:
    assortment: routingKey_James_Assortment

    
    
    
    

